=== rrvbnm/web1/program5_1.dtd
<!ELEMENT studentdetails (students+)>
<!ELEMENT students (USN,Name,College,Branch,Joining,Email)>
<!ELEMENT USN (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT College (#PCDATA)>
<!ELEMENT Branch (#PCDATA)>
<!ELEMENT Joining (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== rrvbnm/web1/program5_2.xml
<?xml version="1.0"?>
<!DOCTYPE studentdetails SYSTEM "program5_1.dtd">
<?xml-stylesheet type="text/xsl" href="program5_3.xsl"?>
<studentdetails>
    <students>
        <USN>4JC14CS134</USN>
        <Name>Rakshith</Name>
        <College>SJCE, Mysuru</College>
        <Branch>Computer Science</Branch>
        <Joining>2014</Joining>
        <Email>rrvbnm@gmail.com</Email>
    </students>
    <students>
        <USN>4NI14CS080</USN>
        <Name>Ravi Teja</Name>
        <College>NIE, Mysuru</College>
        <Branch>Computer Science</Branch>
        <Joining>2014</Joining>
        <Email>ravi.teja@gmail.com</Email>
    </students>
    <students>
        <USN>4JC14IS002</USN>
        <Name>Anup Kalyan</Name>
        <College>SJCE, Mysuru</College>
        <Branch>Information Science</Branch>
        <Joining>2014</Joining>
        <Email>kalyan@gmail.com</Email>
    </students>
</studentdetails>
