=== rrvbnm/web1/program4_1.dtd
<!ELEMENT bookdetails (books+)>
<!ELEMENT books (title,author,edition,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== rrvbnm/web1/program4_2.xml
<?xml version="1.0"?>
<!DOCTYPE bookdetails SYSTEM "program4_1.dtd">
<?xml-stylesheet type="text/xsl" href="program4_3.xsl"?>
<bookdetails>
    <books>
        <title> operating systems principles</title>
        <author> Galvin</author>
        <edition> Seventh edition</edition>
        <price>Rs.500.00</price>
    </books>
    <books>
        <title> Software Engineering </title>
        <author> Pressaman </author>
        <edition> Edition-6</edition>
        <price>Rs. 700.00</price>
    </books>
        <books>
        <title> Communication networks </title>
        <author> leon gracia</author>
        <edition> Edition-IV </edition>
        <price>Rs. 600.00</price>
    </books>
</bookdetails>
